### ISSUE TITLE
How to get the Model of a Vehicle

### ISSUE THREAD

**Issue by krisrandall** [frankely/vin-decoder#18]
This is not an issue, just a question,
How do I obtain the model of a car using this module (and perhaps a suggested supplementary lookup table) ?

**Comment by micaiah-effiong** [comment]
@frankely I would love to work on this and also add typescript support for the package.

**Comment by frankely** [comment]
Go for it @micaiah-effiong create a PR with your proposed changes and I'll make sure to review it and give you all the credit! Thank you for the support.

**Comment by frankely** [comment]
Great work @micaiah-effiong
