### ISSUE TITLE
Improve validity function

### ISSUE THREAD

**Issue by Archigan1** [frankely/vin-decoder#4]
It seems that you need to improve the validity function. Just checking the length isn’t enough. Here are other criteria:

• Cannot have any of I, O, or Q in the VIN
• last five digits have to be numbers
• Check digit needs to be correct

I have a 150-line function that checks for all of this, remind me soon to make a PR.

**Comment by Archigan1** [comment]
Dunnit

**Comment by frankely** [comment]
I merged the PR today.
