### ISSUE TITLE
test cases fail

### ISSUE THREAD

**Issue by darwin2k** [frankely/vin-decoder#6]
Is this validator restricted to VINs from specific countries?

Some test cases breaks for me. The validate function returns false but the VIN seems to be correct.

you can create random VINs here:
https://vingenerator.org/
https://randomvin.com/

https://www.vindecoderz.com/
delivers results for the failing VINs

here are some VIN examples:
WBANF73576CG65408
1D7HA16D94J171206
1G1RC6E41BU103560

**Comment by darwin2k** [comment]
sorry. My test had a bug... the test cases are working now...

**Comment by darwin2k** [comment]
sorry to bother again...

I got confused because there is a npm package with the same name so I accidentally used this. Sor the problem from my post above still persists

**Comment by darwin2k** [comment]
I got even more confused after inspecting the code...

Your switch cases are all lowerCase. VIN normally have uppercase letters, correct?

so maybe there should be
` let splitVIN = vin.toLowerCase().split("");`

At Line 145 the variable is written Uppercase. 
`VIN.split("")[8])`

should be 
`vin.split("")[8])`

Correct me if I am wrong... otherwise I could open a PR

**Comment by frankely** [comment]
@darwin2k I will look into this, I believe the main branch is currently broken.

**Comment by frankely** [comment]
@darwin2k thank you for the feedback. I went ahead and fixed the issue using your suggestion, if you want to contribute to this repo, feel free to create a pull request. I would be happy to add more people!

**Comment by darwin2k** [comment]
@frankely  great, thanks . I will have a look at the code again and try to contribute. good work!
